language: node_js
node_js:
  - 8
sudo:
  - required
services:
  - docker
install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten-slim:sdk-incoming-64bit bash 
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/core.git core
  - cd https://github.com/iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/data.git data
  - cd https://github.com/iota-pico/data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iota-pico/crypto.git crypto
  - cd https://github.com/iota-pico/crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../pow-wasm
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm install
script:
  - npm run wasm-docker || travis_terminate 1
  - npm run dist || travis_terminate 1
#  - npm run security || travis_terminate 1
  - npm run test-publish || travis_terminate 1
cache:
  directories:
    - "node_modules"
