language: node_js
node_js:
  - 8
sudo:
  - required
services:
  - docker
install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten-slim:sdk-incoming-64bit bash 
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-core.git iotaeco/iota-pico-core
  - cd iotaeco/iota-pico-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-data.git iotaeco/iota-pico-data
  - cd iotaeco/iota-pico-data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-crypto.git iotaeco/iota-pico-crypto
  - cd iotaeco/iota-pico-crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../iota-pico-pow-wasm
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm install
script:
  - npm run wasm-docker || travis_terminate 1
  - npm run dist || travis_terminate 1
cache:
  directories:
    - "node_modules"
