language: node_js
node_js:
  - 8
sudo:
  - required
services:
  - docker
before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash 
install:
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-core.git iotaeco/iota-pico-core
  - cd iotaeco/iota-pico-core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-data.git iotaeco/iota-pico-data
  - cd iotaeco/iota-pico-data
  - npm link @iota-pico/core
  - npm link
  - cd ../../
  - git clone --branch=$TRAVIS_BRANCH https://github.com/iotaeco/iota-pico-crypto.git iotaeco/iota-pico-crypto
  - cd iotaeco/iota-pico-crypto
  - npm link @iota-pico/core @iota-pico/data
  - npm link
  - cd ../iota-pico-pow-wasm
  - npm link @iota-pico/core @iota-pico/data @iota-pico/crypto
  - npm install
script:
  - cd src-c
  - docker exec -it emscripten emcc -s USE_PTHREADS=0 -s MODULARIZE=1 -s WASM=1 -s SINGLE_FILE=1 -s \"EXPORTED_FUNCTIONS=['_ccurl_pow']\" -s \"EXTRA_EXPORTED_RUNTIME_METHODS=['ccall', 'cwrap']\" ccurl.c curl.c pearl_diver.c util/converter.c -o ../wasm/iota-pico-pow-wasm.js
  - npm run dist || travis_terminate 1
cache:
  directories:
    - "node_modules"
